### PR TITLE
fix: clean up schema path validation

### LINKED ISSUE #91: Duplicate entries in schemaPaths
image

Throws [ERROR] Failed to execute goal io.github.deweyjose:graphqlcodegen-maven-plugin:1.29:generate (default) on project ***: Execution default of goal io.github.deweyjose:graphqlcodegen-maven-plugin:1.29:generate failed: Duplicate entries in schemaPaths -> [Help 1]

### PR DESCRIPTION
**Pull request by deweyjose**
Clean up schema path validation. The previous checks only considered what was configured. However, DGS will traverse a directory and sub-directories when configured with a directory path as well as any explicit files. If the directory and files overlap this can lead to confusing compiler error messages about duplicate symbols.

This change will ensure no directory ancestral overlap with configured directory or file paths.

fixes #91

### CODE REVIEW

File: src/main/java/io/github/deweyjose/graphqlcodegen/FileReducer.java [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+    Set<File> encounteredDirectories = new HashSet<>();
+    Set<String> encounteredPaths = new HashSet<>();
+
+    for (File file : sortedFiles) {
+      String path = file.getPath();
+
+      // Check for directory overlap
+      File parent = file.getParentFile();
+      if (parent != null && encounteredDirectories.contains(parent)) {
+        throw new IllegalArgumentException(
```
Comment (mjfaga) [inline src/main/java/io/github/deweyjose/graphqlcodegen/FileReducer.java:40]: Why throw an error. Why not skip as you do duplicate files?

File: src/main/java/io/github/deweyjose/graphqlcodegen/FileReducer.java [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+
+      // Check for duplicate files
+      if (encounteredPaths.contains(path)) {
+        continue; // Skip this file, it's a duplicate
+      }
+
+      // Check for ancestry in already added directories
+      while (parent != null) {
+        if (encounteredDirectories.contains(parent)) {
+          throw new IllegalArgumentException(
```
Comment (mjfaga) [inline src/main/java/io/github/deweyjose/graphqlcodegen/FileReducer.java:53]: Same thought here. Can you avoid throwing errors instead?

File: src/main/java/io/github/deweyjose/graphqlcodegen/FileReducer.java (hunk 1 above)
Comment (mjfaga) [reply src/main/java/io/github/deweyjose/graphqlcodegen/FileReducer.java:40]: Maybe a skip + print out a warning?

File: src/main/java/io/github/deweyjose/graphqlcodegen/Validations.java [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+    Set<String> encounteredPaths = new HashSet<>();
+
+    for (File file : sortedFiles) {
+      String path = file.getPath();
+
+      // Check for directory overlap
+      File parent = file.getParentFile();
+      if (parent != null && encounteredDirectories.contains(parent)) {
+        throw new IllegalArgumentException(
+          String.format("Overlap detected: %s contains %s", parent.getPath(), file.getPath())
```
Comment (deweyjose) [inline src/main/java/io/github/deweyjose/graphqlcodegen/Validations.java:40]: @mjfaga sorry I renamed this and lost your comment.

My first thought was to avoid any ambiguity and confusion around misconfig. If configured duplicate directories toss an error and fault, let folks fix the config.

But, looking at this again, its not even possible as `encounteredDirectories` is a set, so it naturally de-dupes. I'll remove this exception.

File: src/main/java/io/github/deweyjose/graphqlcodegen/Validations.java [hunk 4]
```diff
@@ -0,0 +1,70 @@
...
+      // Check for duplicate files
+      if (encounteredPaths.contains(path)) {
+        continue; // Skip this file, it's a duplicate
+      }
+
+      // Check for ancestry in already added directories
+      while (parent != null) {
+        if (encounteredDirectories.contains(parent)) {
+          throw new IllegalArgumentException(
+            String.format("Overlap detected: %s contains %s", parent.getPath(), file.getPath())
```
Comment (deweyjose) [inline src/main/java/io/github/deweyjose/graphqlcodegen/Validations.java:53]: @mjfaga this one is a little trickier. This one catches the case where I've configured `/dir/foo` and `/dir/foo/a.graphqls`. DGS will happily accept both, and will add *all* graphqls files under `/dir/foo` which will process `a.graphqls` twice causing Java compile errors later with generated code.

I think we want to fault here and let folks fix the config, either remove `/dir/foo` or `/dir/foo/a.graphqls`. It's unclear what they want here, the single file or all the files under foo.

File: src/main/java/io/github/deweyjose/graphqlcodegen/Validations.java [hunk 5]
```diff
@@ -0,0 +1,61 @@
...
+
+      // Update the encountered sets
+      if (file.isDirectory()) {
+        encounteredDirectories.add(file);
+      }
+
+      // keep it simple, never allow duplicate configuration
+      if (encounteredPaths.contains(path)) {
+        throw new IllegalArgumentException(
+          String.format("Duplicate path configured: %s", path)
```
Comment (deweyjose) [inline src/main/java/io/github/deweyjose/graphqlcodegen/Validations.java:55]: @mjfaga refactored things a bit. This catches the case where folks misconfigured by adding `/dir` more than once or `/dir/a.graphqls` more than once.

My intention was just validate the config (sorry for the confusion, at one point I thought about being fancier and de-duping but wanted to simplify).

Comment (deweyjose) [reply src/main/java/io/github/deweyjose/graphqlcodegen/Validations.java:55]: I'm not opposed really to shifting back to an approach where we collect and return a valid set of paths if that exists.

File: src/main/java/io/github/deweyjose/graphqlcodegen/Validations.java [hunk 6]
```diff
@@ -0,0 +1,61 @@
...
+      String path = file.getPath();
+
+      // Check for directory overlap
+      File parent = file.getParentFile();
+
+      // Check for ancestry in already added directories
+      while (parent != null) {
+        if (encounteredDirectories.contains(parent)) {
+          throw new IllegalArgumentException(
+            String.format("Overlap configured: %s contains %s", parent.getPath(), file.getPath())
```
Comment (deweyjose) [inline src/main/java/io/github/deweyjose/graphqlcodegen/Validations.java:41]: @mjfaga This one catches the case where I've configured /dir/foo and /dir/foo/a.graphqls. DGS will happily accept both, and will add all graphqls files under /dir/foo which will process a.graphqls twice causing Java compile errors later with generated code.

I think we want to fault here and let folks fix the config, either remove /dir/foo or /dir/foo/a.graphqls. It's unclear what they want here, the single file or all the files under foo.

File: src/main/java/io/github/deweyjose/graphqlcodegen/FileReducer.java (hunk 2 above)
Comment (deweyjose) [reply src/main/java/io/github/deweyjose/graphqlcodegen/FileReducer.java]: this catches the case where they configured `/dir` and `/dir/a.graphls`, its unclear what they want. All the graphqls files under /dir or just a.graphls.

File: src/main/java/io/github/deweyjose/graphqlcodegen/Validations.java (hunk 5 above)
Comment (deweyjose) [reply src/main/java/io/github/deweyjose/graphqlcodegen/Validations.java:55]: actually... this get reduced to Set<File> when it's passed to DGS anyway. I'll remove this, it's not really needed. It's odd to configure like that, but we don't need to throw here.

File: src/main/java/io/github/deweyjose/graphqlcodegen/FileReducer.java (hunk 2 above)
Comment (mjfaga) [reply src/main/java/io/github/deweyjose/graphqlcodegen/FileReducer.java]: Right, which is why the warning would help debug something being included that shouldn’t have been due to misconfiguration.

Comment (deweyjose) [reply src/main/java/io/github/deweyjose/graphqlcodegen/FileReducer.java]: This error shows up in the plug-in output when maven runs

Comment (deweyjose) [reply src/main/java/io/github/deweyjose/graphqlcodegen/FileReducer.java]: And it'll stop maven execution and force developers to fix. Otherwise they run into an error later on in the build that's super confusing
